### ISSUE TITLE
ERROR [RedisModule] default: All sentinels are unreachable. Retrying from scratch after 160ms.

### ISSUE THREAD

**Issue by simplenotezy** [DevAngsy/nestjs-redis#232]
Trying to set up Sentinel, but I am having some issues.

My docker-compose.yaml:

```yaml
  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    restart: always
    ports:
      - 26379:26379
    networks:
      - nestjs-network
    environment:
      - REDIS_MASTER_HOST=redis
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - nestjs-network
    ports:
      - 6379:6379
```

Sentinel seems to be up and running:
```
redis-sentinel 14:59:36.90
redis-sentinel 14:59:36.94 Welcome to the Bitnami redis-sentinel container
redis-sentinel 14:59:36.98 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-sentinel
redis-sentinel 14:59:37.02 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-sentinel/issues
redis-sentinel 14:59:37.06
redis-sentinel 14:59:37.09 INFO  ==> ** Starting Redis sentinel setup **
redis-sentinel 14:59:37.41 INFO  ==> Initializing Redis Sentinel...
redis-sentinel 14:59:37.48 INFO  ==> Configuring Redis Sentinel...
redis-sentinel 14:59:38.35 INFO  ==> ** Redis sentinel setup finished! **

redis-sentinel 14:59:38.50 INFO  ==> ** Starting Redis Sentinel **
1:X 10 Apr 2022 14:59:38.607 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 10 Apr 2022 14:59:38.608 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 10 Apr 2022 14:59:38.608 # Configuration loaded
1:X 10 Apr 2022 14:59:38.611 * monotonic clock: POSIX clock_gettime
1:X 10 Apr 2022 14:59:38.621 * Running mode=sentinel, port=26379.
1:X 10 Apr 2022 14:59:38.650 # Sentinel ID is d1cb69092f21a9c96e793f94cc937c2828b8ab04
1:X 10 Apr 2022 14:59:38.651 # +monitor master mymaster 172.23.0.4 6379 quorum 2
```

My configuration:

```js
return {
	readyLog: true,
	commonOptions: {
		name: 'mymaster',
		sentinels: [
			{
				host: "localhost", // I am running npm locally (not in docker)
				port: 26379,
			},
		],
	},
	config: [
		{
			// get master node from the sentinel group
			role: 'master',
		},
		{
			// get a random slave node from the sentinel group
			role: 'slave',
		},
	],
}
```

But I am getting error:

```
[Nest] 7506  - 04/10/2022, 5:08:21 PM   ERROR [RedisModule] default: All sentinels are unreachable. Retrying from scratch after 130ms.
Error: All sentinels are unreachable. Retrying from scratch after 130ms.
```

What am I missing here?
